#!/usr/bin/env ansible-playbook
---
- hosts: all
  connection: local

  tasks:
    - { include: tasks/chrome.yml, become: yes }
    - { include: tasks/gui-apps.yml, become: yes }
    - { include: tasks/cli-apps.yml, become: yes }
    - include: tasks/unity.yml
