---
- name: Add Google Chrome repo key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub

- name: Add Google Chrome repo
  apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    filename: google-chrome

- name: Install Google Chrome
  apt:
    name: google-chrome-stable
    state: latest
